# Multiple Linear Regression

In [1]:
import numpy as np
import pandas as pd 

In [2]:
# Importing the dataset
dataset = pd.read_csv(r'C:\Users\LENOVO\Ardent ML\Employee_Data.csv')

In [4]:
dataset.head()

Depatment  WorkedHours  Certification  YearsExperience  Salary
0  Development         2300              0              1.1   39343
1      Testing         2100              1              1.3   46205
2  Development         2104              2              1.5   37731
3  UX Designer         1200              1              2.0   43525
4      Testing         1254              2              2.2   39891

In [5]:
X = dataset.iloc[:, :4].values
y = dataset.iloc[:, 4].values

In [7]:
X

array([['Development', 2300, 0, 1.1],
       ['Testing', 2100, 1, 1.3],
       ['Development', 2104, 2, 1.5],
       ['UX Designer', 1200, 1, 2.0],
       ['Testing', 1254, 2, 2.2],
       ['UX Designer', 1236, 1, 2.9],
       ['Development', 1452, 2, 3.0],
       ['Testing', 1789, 1, 3.2],
       ['UX Designer', 1645, 1, 3.2],
       ['UX Designer', 1258, 0, 3.7],
       ['Testing', 1478, 3, 3.9],
       ['Development', 1257, 2, 4.0],
       ['Development', 1596, 1, 4.0],
       ['Testing', 1256, 2, 4.1],
       ['UX Designer', 1489, 3, 4.5],
       ['Development', 1236, 3, 4.9],
       ['Testing', 2311, 2, 5.1],
       ['UX Designer', 2245, 3, 5.3],
       ['Development', 2365, 1, 5.9],
       ['Development', 1500, 3, 6.0],
       ['Testing', 1456, 2, 6.8],
       ['Testing', 1760, 1, 7.1],
       ['UX Designer', 2400, 4, 7.9],
       ['Development', 2148, 3, 8.2],
       ['UX Designer', 1450, 2, 8.7],
       ['UX Designer', 1000, 4, 9.0],
       ['Testing', 1540, 3, 9.5],
       ['D

In [8]:
y

array([ 39343,  46205,  37731,  43525,  39891,  56642,  60150,  54445,
        64445,  57189,  63218,  55794,  56957,  57081,  61111,  67938,
        66029,  83088,  81363,  93940,  91738,  98273, 101302, 113812,
       109431, 105582, 116969, 112635, 122391, 121872], dtype=int64)

In [9]:
#Encoding categorical data
#Doing Label Encoding
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()

X[:, 0] = labelencoder.fit_transform(X[:, 0])
print(X)

[[0 2300 0 1.1]
 [1 2100 1 1.3]
 [0 2104 2 1.5]
 [2 1200 1 2.0]
 [1 1254 2 2.2]
 [2 1236 1 2.9]
 [0 1452 2 3.0]
 [1 1789 1 3.2]
 [2 1645 1 3.2]
 [2 1258 0 3.7]
 [1 1478 3 3.9]
 [0 1257 2 4.0]
 [0 1596 1 4.0]
 [1 1256 2 4.1]
 [2 1489 3 4.5]
 [0 1236 3 4.9]
 [1 2311 2 5.1]
 [2 2245 3 5.3]
 [0 2365 1 5.9]
 [0 1500 3 6.0]
 [1 1456 2 6.8]
 [1 1760 1 7.1]
 [2 2400 4 7.9]
 [0 2148 3 8.2]
 [2 1450 2 8.7]
 [2 1000 4 9.0]
 [1 1540 3 9.5]
 [0 1500 2 9.6]
 [1 3000 4 10.3]
 [2 2100 3 10.5]]


In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split(X, y,test_size = .25, random_state = 42) 

In [11]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)
y_pred=regressor.predict(X_test)

## R2 score

Return the coefficient of determination R^2 
of the prediction. The coefficient R^2 is defined
 as (1 - u/v), where u is the residual sum of 
 squares ((y_test - y_pred) ** 2).sum() and v is 
 the total sum of squares
 ((y_test - y_test.mean()) ** 2).sum(). 
 The best possible score is 1.0 and it can be
 negative (because the model can be arbitrarily worse).
 A constant model that always predicts the expected
 value of y, disregarding the input features, 
 would get a R^2 score of 0.0.

In [12]:
accuracy = (regressor.score(X_test,y_pred))
print("Accuracy=",accuracy)

Accuracy= 1.0


In [14]:
from sklearn import metrics
print("Error:",np.sqrt(metrics.mean_squared_error(y_test,y_pred)))

Error: 6277.253591090725


In [15]:
print("result",regressor.predict(np.array([0, 2300, 0, 1.1]).reshape(1,4)))


result [38068.35199995]


In [16]:
print("result2",regressor.predict([[1, 2300, 0, 1.1]]))


result2 [37074.50056017]
